package `in`.sarangal.lib.spantastic

import android.graphics.Typeface
import androidx.annotation.Keep

/**
 * Developed with Love by Sarangal
 */

/**
 * Class Params:
 *
 * @param textSize     PIXEL value in Float type for TextSize.
 * @param spanString   String which will be convert to spannable.
 * @param colorId      The desired resource identifier, as generated by the aapt
 * tool. This integer encodes the package, type, and resource
 * entry. The value 0 is an invalid identifier.
 * @param callbackKey  The key with return with click on spannable.
 * @param showUnderline true: underline will be display under span text,
 * false: no underline
 * @param typeface     Typeface for custom styling.
 */
@Keep
data class SpanModel(
    val spanString: String,
    val colorId: Int? = null,
    val callbackKey: String,
    val showUnderline: Boolean? = null,
    val typeface: Typeface? = null,
    val textSize: Float? = null
)