package in.sarangal.lib.spantastic;

import android.graphics.Typeface;

import androidx.annotation.NonNull;

/**
 * Developed with Love by Sarangal
 */

public class SpanModel {

    private String mSpanString;
    private Integer mColorId;
    private String mCallbackKey;
    private Boolean showUnderline;
    private Typeface mTypeface;
    private Float mTextSize;

    public Float getTextSize() {
        return mTextSize;
    }

    public Typeface getTypeface() {
        return mTypeface;
    }

    public String getSpanString() {
        return mSpanString;
    }

    public Integer getColorId() {
        return mColorId;
    }

    public String getCallbackKey() {
        return mCallbackKey;
    }

    public Boolean getShowUnderline() {
        return showUnderline;
    }

    /**
     * Method Params:
     *
     * @param mTextSize     PIXEL value in Float type for TextSize.
     * @param mSpanString   String which will be convert to spannable.
     * @param mColorId      The desired resource identifier, as generated by the aapt
     *                      tool. This integer encodes the package, type, and resource
     *                      entry. The value 0 is an invalid identifier.
     * @param mCallbackKey  The key with return with click on spannable.
     * @param showUnderline true: underline will be display under span text,
     *                      false: no underline
     * @param mTypeface     Typeface for custom styling.
     */

    public SpanModel(@NonNull String mSpanString, Integer mColorId, @NonNull String mCallbackKey, Boolean showUnderline, Typeface mTypeface, Float mTextSize) {
        this.mSpanString = mSpanString;
        this.mColorId = mColorId;
        this.mCallbackKey = mCallbackKey;
        this.showUnderline = showUnderline;
        this.mTypeface = mTypeface;
        this.mTextSize = mTextSize;
    }

}
